---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{values.namespace_id}}-admin
  namespace: ${{values.namespace_id}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: User
    name: ${{values.owner}}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
