---
apiVersion: v1
kind: Namespace
metadata:
  name: ${{values.namespace_id}}
  labels:
    environment: ${{values.environment}}
    managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
