# Default values for tomcat-vm
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  name: ${{values.component_id}}
  namespace: ${{values.namespace}}
  cluster: ${{values.cluster}}

git:
  branch: main
  repo: ${{values.source_repository}}
  org: ${{values.org}}
  name: ${{values.repository_name}}
  host: ${{values.git_host}}

nameOverride: ""
fullnameOverride: ""


targetEnvironment: dev
env: []

namespacePermissions:
  # Which OpenShift user gets permissions for the namespace
  user: kubeadmin
  # Which role to grant the user on the namespace
  role: admin

resources:
  requests:
    memory: 4Gi
    cpu: 2

storage:
  pvcSize: 40Gi

datasource:
  name: ${{values.datasource_name}}
  namespace: ${{values.datasource_namespace}}

nodeSelector: {}

tolerations: []

staticIP: ""
# staticIP: "10.10.10.31/24"
